g++ -c main.cpp -I /home/morda/dev/gravity/sfml-sources/SFML-2.3/include -I /home/morda/dev/gravity/box2d-sources/Box2D-master/Box2D/
echo main.o generated ...
g++ main.o -o sfml-app -L/home/morda/dev/gravity/sfml-sources/SFML-2.3/lib -lsfml-graphics-d -lsfml-window-d -lsfml-system-d -L/home/morda/dev/gravity/box2d-sources/Box2D-master/Box2D/Box2D -lBox2D
echo main.o compiled ...
